import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { ThemeProvider } from "@/components/theme-provider";
import ClientProviders from "@/providers/query-client-provider";
import { AnalyticsProvider } from "@/providers/posthog-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`overscroll-none antialiased font-sans bg-[#0c0e11] min-w-[320px]`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <ClientProviders>
            <AnalyticsProvider>
              <SidebarProvider defaultOpen={false}>
                <AppSidebar />
                <main className="flex-1">{children}</main>
              </SidebarProvider>
            </AnalyticsProvider>
          </ClientProviders>
        </ThemeProvider>
      </body>
    </html>
  );
}
